version: "3.8"
services:
  mysql:
      image: mysql:8.0
      container_name: ${MYSQL_CONTAINER_NAME}
      restart: always
      ports: 
       - "${MYSQL_PORT}:3306"
      environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}              
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      volumes:
        - mysql_data:/var/lib/mysql
volumes:
  mysql_data: